### PR TITLE
Upgrade dependencies to the latest stable angular.js

### PR DESCRIPTION
**Pull request by dkokic**

### CODE REVIEW

**Comment by phra** [comment]
@dkokic can you confirm that the project will work without problem w/ angular 1.6 ?

**Comment by dkokic** [comment]
@phra I use angular.js 1.7 at my work projects and have just updated the PR.

**Comment by dkokic** [comment]
done ;-)

**Comment by phra** [comment]
@dkokic thanks for the contributions! :100:

**Pull request merged**
